export type PlayerType = 'Player' | 'GameMaster';

export interface Character {
  id: string;
  name: string;
  playerName: string;
  hope: number;
  stress: number;
  maxStress: number;
  hitPoints: number;
  maxHitPoints: number;
  armorSlots: number;
  maxArmorSlots: number;
  deviceId: string;
  createdAt?: Date;
}

export interface Game {
  id: string;
  name: string;
  gameMasterName: string;
  fear: number;
  shareCode: string;
  deviceId: string;
  createdAt?: Date;
}

// fields a user edits on an existing Game
export type GameInput = Pick<Game, 'name' | 'gameMasterName' | 'fear'>;

// everything needed to create a Game; the id is generated by Firestore
export type NewGameInput = GameInput & Pick<Game, 'shareCode' | 'deviceId'>;
