export interface Character {
  id: string;
  name: string;
  playerName: string;
  hope: number;
  stress: number;
  maxStress: number;
  hitPoints: number;
  maxHitPoints: number;
  armorSlots: number;
  maxArmorSlots: number;
  deviceId: string;
  createdAt?: string; // ISO 8601, set by Firestore's serverTimestamp()
  lastModifiedAt?: string; // ISO 8601, set by Firestore's serverTimestamp()
}

export interface Game {
  id: string;
  name: string;
  gameMasterName: string;
  fear: number;
  shareCode: string;
  deviceId: string;
  createdAt?: string; // ISO 8601, set by Firestore's serverTimestamp()
  lastModifiedAt?: string; // ISO 8601, set by Firestore's serverTimestamp()
}

// fields a user edits on an existing Game
export type GameInput = Pick<Game, 'name' | 'gameMasterName' | 'fear'>;

// everything needed to create a Game; the id is generated by Firestore
export type NewGameInput = GameInput & Pick<Game, 'shareCode' | 'deviceId'>;

// fields a user edits on an existing Character
export type CharacterInput = Omit<Character, 'id' | 'deviceId' | 'createdAt'>;

// everything needed to create a Character; the id is generated by Firestore
export type NewCharacterInput = CharacterInput & Pick<Character, 'deviceId'>;
